acc_cluster:
  - Name: body
  - DMA:
    - Name: body_dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
  - DMA:
    - Name: body_stream_dma0
      PIOMaster: LocalBus
      StreamSize: 8
      BufferSize: 64
      Type: Stream
      ReadInt: 212
      WriteInt: 213
  - DMA:
    - Name: body_stream_dma1
      PIOMaster: LocalBus
      StreamSize: 8
      BufferSize: 64
      Type: Stream
      ReadInt: 214
      WriteInt: 215
  - Accelerator:
    - Name: body_top
      IrPath: /hw/ir/body/top.ll
      ConfigPath: /hw/configs/body/top.ini
      Debug: False
      PIOSize: 81
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
  - Accelerator:
    - Name: body_residual
      IrPath: /hw/ir/body/Residual.ll
      ConfigPath: /hw/configs/body/Residual.ini
      Debug: False
      PIOSize: 17
      PIOMaster: LocalBus
      StreamOut: body_stream_dma0,body_stream_dma1
    - Var:
      - Name: body_ResidualOut
        Type: Stream
        StreamSize: 8
        BufferSize: 64
        InCon: body_residual
        OutCon: body_PWConv0
  - Accelerator:
    - Name: body_PWConv0
      IrPath: /hw/ir/body/PWConv0.ll
      ConfigPath: /hw/configs/body/PWConv0.ini
      Debug: False
      PIOSize: 57
      PIOMaster: LocalBus
    - Var:
      - Name: body_PWConv0LocalFeats
        Type: SPM
        Size: 120
        Ports: 120
    - Var:
      - Name: body_PWConv0Weights
        Type: SPM
        Size: 86400
        Ports: 120
    - Var:
      - Name: body_PW0Bias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PW0IMultBias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PW0NShiftBias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PW0IMultOut
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PW0NShiftOut
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PW0WeightZP
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_PWConv0Out
        Type: Stream
        StreamSize: 8
        BufferSize: 64
        InCon: body_PWConv0
        OutCon: body_DWConv
  - Accelerator:
    - Name: body_DWConv
      IrPath: /hw/ir/body/DWConv.ll
      ConfigPath: /hw/configs/body/DWConv.ini
      Debug: False
      PIOSize: 65
      PIOMaster: LocalBus
    - Var:
      - Name: body_DWConvWindow
        Type: SPM
        Size: 6480
        Ports: 9
    - Var:
      - Name: body_DWConvWeights
        Type: SPM
        Size: 7200
        Ports: 9
    - Var:
      - Name: body_DWBias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWIMultBias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWNShiftBias
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWIMultOut
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWNShiftOut
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWWeightZP
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWConvBuffer
        Type: SPM
        Size: 69120
        Ports: 2
    - Var:
      - Name: body_DWConvOutBuffer
        Type: SPM
        Size: 720
        Ports: 1
    - Var:
      - Name: body_DWConvOut
        Type: Stream
        StreamSize: 8
        BufferSize: 64
        InCon: body_DWConv
        OutCon: body_PWConv1
  - Accelerator:
    - Name: body_PWConv1
      IrPath: /hw/ir/body/PWConv1.ll
      ConfigPath: /hw/configs/body/PWConv1.ini
      Debug: False
      PIOSize: 57
      PIOMaster: LocalBus
      StreamIn: body_stream_dma0
    - Var:
      - Name: body_PWConv1LocalFeats
        Type: SPM
        Size: 720
        Ports: 120
    - Var:
      - Name: body_PWConv1Weights
        Type: SPM
        Size: 172800
        Ports: 120
    - Var:
      - Name: body_PW1Bias
        Type: SPM
        Size: 240
        Ports: 1
    - Var:
      - Name: body_PW1IMultBias
        Type: SPM
        Size: 240
        Ports: 1
    - Var:
      - Name: body_PW1NShiftBias
        Type: SPM
        Size: 240
        Ports: 1
    - Var:
      - Name: body_PW1IMultOut
        Type: SPM
        Size: 240
        Ports: 1
    - Var:
      - Name: body_PW1NShiftOut
        Type: SPM
        Size: 240
        Ports: 1
    - Var:
      - Name: body_PW1WeightZP
        Type: SPM
        Size: 240
        Ports: 1
