---
acc_cluster:
  - Name: lenet5_clstr
  - DMA:
    - Name: dma
      BufferSize: 64
      MaxReqSize: 8
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: top
      IrPath: hw/ir/top.ll
      PIOSize: 17
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
      Debug: False
      InterruptNum: 68
  - Accelerator:
    - Name: conv0
      IrPath: hw/ir/conv0.ll
      Debug: True
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv0Input
        Type: SPM
        Size: 4096
        Ports: 150
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
    - Var:
      - Name: Conv0Weights
        Type: SPM
        Size: 600
        Ports: 150
    - Var:
      - Name: Conv0Output
        Type: SPM
        Size: 18816
        Ports: 6
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_0:6

  - Accelerator:
    - Name: data_mover_0
      IrPath: hw/ir/data_mover_0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: pool0
      IrPath: hw/ir/pool0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: pool0Input
        Type: SPM
        Size: 18816
        Ports: 24
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_0:24
    - Var:
      - Name: pool0Output
        Type: SPM
        Size: 4704
        Ports: 6
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_1:6
  - Accelerator:
    - Name: data_mover_1
      IrPath: hw/ir/data_mover_1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: conv1
      IrPath: hw/ir/conv1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv1Input
        Type: SPM
        Size: 4704
        Ports: 2400
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_1:2400
    - Var:
      - Name: Conv1Weights
        Type: SPM
        Size: 9600
        Ports: 2400
    - Var:
      - Name: Conv1Output
        Type: SPM
        Size: 6400
        Ports: 16
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_2:16

  - Accelerator:
    - Name: data_mover_2
      IrPath: hw/ir/data_mover_2.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: pool1
      IrPath: hw/ir/pool1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: pool1Input
        Type: SPM
        Size: 6400
        Ports: 64
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_2:64
    - Var:
      - Name: pool1Output
        Type: SPM
        Size: 1600
        Ports: 16
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_3:16
  - Accelerator:
    - Name: data_mover_3
      IrPath: hw/ir/data_mover_3.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: conv2
      IrPath: hw/ir/conv2.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: conv2Input
        Type: SPM
        Size: 1600
        Ports: 1200
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_3:16
    - Var:
      - Name: conv2Weights
        Type: SPM
        Size: 192000
        Ports: 1200
    - Var:
      - Name: conv2Output
        Type: SPM
        Size: 480
        Ports: 120
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_4:120
  - Accelerator:
    - Name: data_mover_4
      IrPath: hw/ir/data_mover_4.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: fc0
      IrPath: hw/ir/fc0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: fc0Input
        Type: SPM
        Size: 480
        Ports: 120
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
        Connections: data_mover_4:120
    - Var:
      - Name: fc0Weights
        Type: SPM
        Size: 40320
        Ports: 120
    - Var:
      - Name: fc0Output
        Type: SPM
        Size: 336
        Ports: 120
        ReadyMode: True
        ResetOnRead: False
        WriteOnValid: False
hw_config:
  top:
  conv0:
  conv1:
  conv2:
  fc0:
  pool0:
  pool1:
  fc1: